<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <listeners>
    <listener class-name="utility.FailureCapture"/>
  </listeners>
  <test thread-count="5" name="functional(failed)">
    <classes>
      <class name="testcases.YourCartTestCases">
        <methods>
          <include name="tear"/>
          <include name="setup"/>
          <include name="YourCart"/>
        </methods>
      </class> <!-- testcases.YourCartTestCases -->
      <class name="testcases.SelectProductTestCase">
        <methods>
          <include name="tear"/>
          <include name="setup"/>
          <include name="SelectProduct"/>
        </methods>
      </class> <!-- testcases.SelectProductTestCase -->
      <class name="testcases.LoginTestCases">
        <methods>
          <include name="tear"/>
          <include name="setup"/>
          <include name="verifyUser" invocation-numbers="0 1 2 3"/>
        </methods>
      </class> <!-- testcases.LoginTestCases -->
      <class name="testcases.AddressAndContinueTestCases">
        <methods>
          <include name="tear"/>
          <include name="setup"/>
          <include name="AddressAndContinue"/>
        </methods>
      </class> <!-- testcases.AddressAndContinueTestCases -->
    </classes>
  </test> <!-- functional(failed) -->
</suite> <!-- Failed suite [Suite] -->
